# Custom Language File for Launcher Customizer

[ejs.app]
title = "Esme Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BONJOUR"
welcomeDescription = "Vous etes ici sur le luncher officielle de l'ESME, ce luncher a ete develope sur la base de l'Elios Luncher et modifier et adapter par le BDJ (bureau des jeux), de l'Esme (Ecole generaliste d'ingenieur). Vous retrouverez touts les liens de l'ecole une fois que vous vous serez connecter.Amusez vous bien !! "
welcomeDescCTA = "Vous n'estes plus qu'a quelques clicks !."
